default_language_version:
    python: python3.9
repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        additional_dependencies:
        -   toml
        exclude: "example/"
-   repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python3 -m pylint
        language: system
        types: [python]
        exclude: "example/"
      - id: mypy
        name: mypy
        entry: python3 -m mypy
        args: ["--junit-xml", "test-reports/mypy-junit.xml"]
        language: system
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
