name: Publish Python package

on:
  push:
    tags:
      - '[0-2].[0-9]+.[0-9]+*'

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Build and Publish package
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry build
        poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
